ALTER TABLE "Product"
ADD COLUMN IF NOT EXISTS "hasPriceVariants" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "commercialPrice" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "pratoFeitoPrice" DECIMAL(10,2);

ALTER TABLE "OrderItem"
ADD COLUMN IF NOT EXISTS "priceVariant" TEXT;
